/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    ClearButton: typeof import('./src/components/ClearButton.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    CopySuccessSnackbar: typeof import('./src/components/CopySuccessSnackbar.vue')['default']
    CurrentTimestamp: typeof import('./src/components/generators/CurrentTimestamp.vue')['default']
    GeneratorExpansionPanel: typeof import('./src/components/generators/GeneratorExpansionPanel.vue')['default']
    GeneratorInput: typeof import('./src/components/generators/GeneratorInput.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    NanoId: typeof import('./src/components/generators/NanoId.vue')['default']
    RegenerateButton: typeof import('./src/components/RegenerateButton.vue')['default']
    ReleaseNotesItem: typeof import('./src/components/ReleaseNotesItem.vue')['default']
    SnowflakeId: typeof import('./src/components/generators/SnowflakeId.vue')['default']
    Ulid: typeof import('./src/components/generators/Ulid.vue')['default']
    UuidEmpty: typeof import('./src/components/generators/UuidEmpty.vue')['default']
    UuidV4: typeof import('./src/components/generators/UuidV4.vue')['default']
    UuidV7: typeof import('./src/components/generators/UuidV7.vue')['default']
    Xid: typeof import('./src/components/generators/Xid.vue')['default']
  }
}
