/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    CasingSelector: typeof import('./src/components/CasingSelector.vue')['default']
    ClearBtn: typeof import('./src/components/ClearBtn.vue')['default']
    CopyBtn: typeof import('./src/components/CopyBtn.vue')['default']
    Cuid2: typeof import('./src/components/generators/Cuid2.vue')['default']
    GeneratorExpansionPanel: typeof import('./src/components/GeneratorExpansionPanel.vue')['default']
    GeneratorInput: typeof import('./src/components/GeneratorInput.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    MongoObjectId: typeof import('./src/components/generators/MongoObjectId.vue')['default']
    NanoId: typeof import('./src/components/generators/NanoId.vue')['default']
    RandomString: typeof import('./src/components/generators/RandomString.vue')['default']
    RegenerateBtn: typeof import('./src/components/RegenerateBtn.vue')['default']
    ResetAppStateDialog: typeof import('./src/components/ResetAppStateDialog.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SnowflakeId: typeof import('./src/components/generators/SnowflakeId.vue')['default']
    SwitchThemeListItem: typeof import('./src/components/SwitchThemeListItem.vue')['default']
    Timestamp: typeof import('./src/components/generators/Timestamp.vue')['default']
    Ulid: typeof import('./src/components/generators/Ulid.vue')['default']
    Uuid: typeof import('./src/components/generators/Uuid.vue')['default']
    UuidBase: typeof import('./src/components/generators/UuidBase.vue')['default']
    UuidFormatSelector: typeof import('./src/components/UuidFormatSelector.vue')['default']
    UuidFunctionSelector: typeof import('./src/components/UuidFunctionSelector.vue')['default']
    UuidStatic: typeof import('./src/components/generators/UuidStatic.vue')['default']
    Xid: typeof import('./src/components/generators/Xid.vue')['default']
  }
}
