/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/AboutDialog.vue')['default']
    ClearButton: typeof import('./src/components/ClearButton.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    Cuid2: typeof import('./src/components/generators/Cuid2.vue')['default']
    GeneratorExpansionPanel: typeof import('./src/components/GeneratorExpansionPanel.vue')['default']
    GeneratorInput: typeof import('./src/components/GeneratorInput.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    MongoObjectId: typeof import('./src/components/generators/MongoObjectId.vue')['default']
    NanoId: typeof import('./src/components/generators/NanoId.vue')['default']
    RegenerateButton: typeof import('./src/components/RegenerateButton.vue')['default']
    ReleaseNotesItem: typeof import('./src/components/ReleaseNotesItem.vue')['default']
    ResetAppStateDialog: typeof import('./src/components/ResetAppStateDialog.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SnowflakeId: typeof import('./src/components/generators/SnowflakeId.vue')['default']
    Timestamp: typeof import('./src/components/generators/Timestamp.vue')['default']
    Ulid: typeof import('./src/components/generators/Ulid.vue')['default']
    UuidMax: typeof import('./src/components/generators/UuidMax.vue')['default']
    UuidNil: typeof import('./src/components/generators/UuidNil.vue')['default']
    UuidV4: typeof import('./src/components/generators/UuidV4.vue')['default']
    UuidV7: typeof import('./src/components/generators/UuidV7.vue')['default']
    Xid: typeof import('./src/components/generators/Xid.vue')['default']
  }
}
